// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super_Cartes_Infinies.Data;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("DeckOwnedCard", b =>
                {
                    b.Property<int>("DecksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnedCardsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DecksId", "OwnedCardsId");

                    b.HasIndex("OwnedCardsId");

                    b.ToTable("DeckOwnedCard");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111112",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eebe3f9c-a612-4e7e-b9e9-502f59b2383a",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIYlrpCXQ9ikWAqOrUj5892FwIQx/Uj6PvvSZImyXL55VCeKUvdB2ii8L6Su91iTYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a227b12b-8d0e-4ff9-9e55-e7b79474fa38",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "User1Id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6510b788-32f1-4147-9019-ed009ae024ae",
                            Email = "jean@jean.jean",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "JEAN@JEAN.COM",
                            NormalizedUserName = "JEAN",
                            PasswordHash = "AQAAAAIAAYagAAAAENsyyWpWoH9GVgSCf41d+IHeMCsU7sMbRkcskhhtcycGCx2J0Tr0xAZNX3oPSz+HnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a670404-34d9-4e3e-ad6c-84a4b8f74d6e",
                            TwoFactorEnabled = false,
                            UserName = "Jean"
                        },
                        new
                        {
                            Id = "User2Id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96af5e4e-0356-420c-a48b-a4fd1c95908c",
                            Email = "bob@bob.bob",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "BOB@BOB.COM",
                            NormalizedUserName = "BOB",
                            PasswordHash = "AQAAAAIAAYagAAAAEE7ga7SdEwincsKr70qDxnImjFe/ajp+Tyztw7K0noaU+1623jgji1saiK9OSVossA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee2d119d-077c-4923-bb43-1ad0198e958b",
                            TwoFactorEnabled = false,
                            UserName = "Bob"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111111",
                            RoleId = "11111111-1111-1111-1111-111111111112"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Models.CardPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PowerId");

                    b.ToTable("CardPowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 6,
                            PowerId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 2,
                            CardId = 4,
                            PowerId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            CardId = 5,
                            PowerId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            CardId = 3,
                            PowerId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 5,
                            CardId = 6,
                            PowerId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 6,
                            CardId = 3,
                            PowerId = 8,
                            Value = 2
                        },
                        new
                        {
                            Id = 7,
                            CardId = 13,
                            PowerId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            CardId = 15,
                            PowerId = 10,
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            CardId = 5,
                            PowerId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            CardId = 8,
                            PowerId = 9,
                            Value = 5
                        },
                        new
                        {
                            Id = 11,
                            CardId = 14,
                            PowerId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 12,
                            CardId = 9,
                            PowerId = 7,
                            Value = 1
                        });
                });

            modelBuilder.Entity("Models.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nbDefaites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nbVictoires")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Models.Models.OwnedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("OwnedCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            PlayerId = "User1Id"
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            PlayerId = "User1Id"
                        },
                        new
                        {
                            Id = 3,
                            CardId = 3,
                            PlayerId = "User1Id"
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            PlayerId = "User1Id"
                        },
                        new
                        {
                            Id = 5,
                            CardId = 5,
                            PlayerId = "User1Id"
                        },
                        new
                        {
                            Id = 6,
                            CardId = 6,
                            PlayerId = "User1Id"
                        },
                        new
                        {
                            Id = 7,
                            CardId = 7,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 8,
                            CardId = 8,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 9,
                            CardId = 9,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 10,
                            CardId = 10,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 11,
                            CardId = 1,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 12,
                            CardId = 2,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 13,
                            CardId = 3,
                            PlayerId = "User2Id"
                        },
                        new
                        {
                            Id = 14,
                            CardId = 4,
                            PlayerId = "User2Id"
                        });
                });

            modelBuilder.Entity("Models.Models.Paquet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NbCartes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RareteParDefaut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Paquets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 500,
                            ImageUrl = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4f7705ec-8c49-4eed-a56e-c21f3985254c/dah43cy-a8e121cb-934a-40f6-97c7-fa2d77130dd5.png/v1/fill/w_1024,h_1420/pokemon_card_backside_in_high_resolution_by_atomicmonkeytcg_dah43cy-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTQyMCIsInBhdGgiOiJcL2ZcLzRmNzcwNWVjLThjNDktNGVlZC1hNTZlLWMyMWYzOTg1MjU0Y1wvZGFoNDNjeS1hOGUxMjFjYi05MzRhLTQwZjYtOTdjNy1mYTJkNzcxMzBkZDUucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.9GzaYS7sd8RPY5FlHca09J9ZQZ9D9zI69Ru-BsbkLDA",
                            Name = "Basic",
                            NbCartes = 3,
                            RareteParDefaut = 0
                        },
                        new
                        {
                            Id = 2,
                            Cost = 1000,
                            ImageUrl = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4f7705ec-8c49-4eed-a56e-c21f3985254c/dah43cy-a8e121cb-934a-40f6-97c7-fa2d77130dd5.png/v1/fill/w_1024,h_1420/pokemon_card_backside_in_high_resolution_by_atomicmonkeytcg_dah43cy-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTQyMCIsInBhdGgiOiJcL2ZcLzRmNzcwNWVjLThjNDktNGVlZC1hNTZlLWMyMWYzOTg1MjU0Y1wvZGFoNDNjeS1hOGUxMjFjYi05MzRhLTQwZjYtOTdjNy1mYTJkNzcxMzBkZDUucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.9GzaYS7sd8RPY5FlHca09J9ZQZ9D9zI69Ru-BsbkLDA",
                            Name = "Normal",
                            NbCartes = 4,
                            RareteParDefaut = 0
                        },
                        new
                        {
                            Id = 3,
                            Cost = 2000,
                            ImageUrl = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4f7705ec-8c49-4eed-a56e-c21f3985254c/dah43cy-a8e121cb-934a-40f6-97c7-fa2d77130dd5.png/v1/fill/w_1024,h_1420/pokemon_card_backside_in_high_resolution_by_atomicmonkeytcg_dah43cy-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTQyMCIsInBhdGgiOiJcL2ZcLzRmNzcwNWVjLThjNDktNGVlZC1hNTZlLWMyMWYzOTg1MjU0Y1wvZGFoNDNjeS1hOGUxMjFjYi05MzRhLTQwZjYtOTdjNy1mYTJkNzcxMzBkZDUucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.9GzaYS7sd8RPY5FlHca09J9ZQZ9D9zI69Ru-BsbkLDA",
                            Name = "Super",
                            NbCartes = 5,
                            RareteParDefaut = 1
                        });
                });

            modelBuilder.Entity("Models.Models.PlayableCardStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayableCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayableCardId");

                    b.HasIndex("StatusId");

                    b.ToTable("PlayableCardStatus");
                });

            modelBuilder.Entity("Models.Models.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Powers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ça assault",
                            Icone = "🦍",
                            Name = "Assault"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ça piquotte",
                            Icone = "💒",
                            Name = "Piquotte"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ça soin",
                            Icone = "🙇‍♂️",
                            Name = "Soin"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ça nuke",
                            Icone = "☢",
                            Name = "Nuke"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ça chaos pas mal",
                            Icone = "💥",
                            Name = "Chaos"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ça shake",
                            Icone = "🌎",
                            Name = "Earthquake"
                        },
                        new
                        {
                            Id = 7,
                            Description = "T'as mal mais tu sais pas pourquoi",
                            Icone = "⁉",
                            Name = "Random Pain"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ça em🐟e",
                            Icone = "🐟",
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ça stun",
                            Icone = "💫",
                            Name = "Stun"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Offre un abonnement Tinder Premium",
                            Icone = "💕",
                            Name = "Charme"
                        });
                });

            modelBuilder.Entity("Models.Models.Probability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaquetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Probabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseQty = 0,
                            PaquetName = "Basic",
                            Rarity = 1,
                            Value = 0.3m
                        },
                        new
                        {
                            Id = 2,
                            BaseQty = 1,
                            PaquetName = "Normal",
                            Rarity = 1,
                            Value = 0.3m
                        },
                        new
                        {
                            Id = 3,
                            BaseQty = 0,
                            PaquetName = "Normal",
                            Rarity = 2,
                            Value = 0.1m
                        },
                        new
                        {
                            Id = 4,
                            BaseQty = 0,
                            PaquetName = "Normal",
                            Rarity = 3,
                            Value = 0.02m
                        },
                        new
                        {
                            Id = 5,
                            BaseQty = 1,
                            PaquetName = "Super",
                            Rarity = 2,
                            Value = 0.25m
                        },
                        new
                        {
                            Id = 6,
                            BaseQty = 0,
                            PaquetName = "Super",
                            Rarity = 3,
                            Value = 0.1m
                        },
                        new
                        {
                            Id = 7,
                            BaseQty = 0,
                            PaquetName = "Super",
                            Rarity = 0,
                            Value = 0m
                        });
                });

            modelBuilder.Entity("Models.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ça em🐟e",
                            Icone = "🦍",
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ça stun",
                            Icone = "💫",
                            Name = "Stunned"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ça charmé",
                            Icone = "💕",
                            Name = "Charmed"
                        });
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarete")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 5,
                            Cost = 4,
                            Health = 3,
                            ImageUrl = "https://i.imgur.com/8iWUCdM.gif",
                            Name = "Jarvisse",
                            Rarete = "Épique"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 12,
                            Cost = 3,
                            Health = 1,
                            ImageUrl = "https://media1.tenor.com/m/xCK-Co72KrIAAAAd/jerma-jerma-sus.gif",
                            Name = "Jermasouss",
                            Rarete = "Épique"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 2,
                            Cost = 4,
                            Health = 8,
                            ImageUrl = "https://media.tenor.com/rPPN4J5vv2UAAAAM/rizzler-costco.gif",
                            Name = "Evil Rizzled",
                            Rarete = "Légendaire"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 8,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://i.imgur.com/T7FZVSU.gif",
                            Name = "Jarvousse",
                            Rarete = "Légendaire"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 2,
                            Cost = 2,
                            Health = 2,
                            ImageUrl = "https://media1.tenor.com/m/DRBLpAd8zVIAAAAd/dog-whimsical.gif",
                            Name = "Arf",
                            Rarete = "Commune"
                        },
                        new
                        {
                            Id = 6,
                            Attack = 0,
                            Cost = 4,
                            Health = 9,
                            ImageUrl = "https://i.pinimg.com/originals/87/ea/89/87ea8952891e51553d55d90dc649bbf3.gif",
                            Name = "Lemur",
                            Rarete = "Commune"
                        },
                        new
                        {
                            Id = 7,
                            Attack = 2,
                            Cost = 4,
                            Health = 6,
                            ImageUrl = "https://media1.tenor.com/m/ShtsLOsS2e4AAAAd/freaky-tree.gif",
                            Name = "Écorceur Farceur",
                            Rarete = "Rare"
                        },
                        new
                        {
                            Id = 8,
                            Attack = 1,
                            Cost = 2,
                            Health = 4,
                            ImageUrl = "https://media1.tenor.com/m/JWPDuXIDQukAAAAd/cat-osu.gif",
                            Name = "Evil Kitty",
                            Rarete = "Commune"
                        },
                        new
                        {
                            Id = 9,
                            Attack = 0,
                            Cost = 3,
                            Health = 0,
                            ImageUrl = "/assets/tom.gif",
                            Name = "Tom Farceur",
                            Rarete = "Rare"
                        },
                        new
                        {
                            Id = 10,
                            Attack = 6,
                            Cost = 2,
                            Health = 1,
                            ImageUrl = "https://media1.tenor.com/m/LmK9TOuC1msAAAAd/thats-class-lets-go.gif",
                            Name = "Bathieu",
                            Rarete = "Rare"
                        },
                        new
                        {
                            Id = 11,
                            Attack = 10,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://static.wikia.nocookie.net/beegyoshi/images/e/e6/HoCa.jpg",
                            Name = "Hogan's Castle.",
                            Rarete = "Épique"
                        },
                        new
                        {
                            Id = 12,
                            Attack = 2,
                            Cost = 3,
                            Health = 5,
                            ImageUrl = "https://media.tenor.com/uPmcmIaUtvoAAAAM/john-pork-pork.gif",
                            Name = "John Pork",
                            Rarete = "Commune"
                        },
                        new
                        {
                            Id = 13,
                            Attack = 0,
                            Cost = 3,
                            Health = 10,
                            ImageUrl = "https://i.kym-cdn.com/entries/icons/original/000/043/174/cover12.jpg",
                            Name = "Hydrogen Bomb VS Coughing Baby",
                            Rarete = "Légendaire"
                        },
                        new
                        {
                            Id = 14,
                            Attack = 0,
                            Cost = 5,
                            Health = 0,
                            ImageUrl = "https://i.imgur.com/35y49Rq.png",
                            Name = "FIGUE BANANE NOIX!!!",
                            Rarete = "Légendaire"
                        },
                        new
                        {
                            Id = 15,
                            Attack = 1,
                            Cost = 5,
                            Health = 10,
                            ImageUrl = "/assets/cedric.jpg",
                            Name = "Cédrouc",
                            Rarete = "Rare"
                        },
                        new
                        {
                            Id = 16,
                            Attack = 5,
                            Cost = 3,
                            Health = 2,
                            ImageUrl = "https://cdn-images.dzcdn.net/images/cover/4937906affa0da23fabba7f104b84bf1/0x1900-000000-80-0-0.jpg",
                            Name = "Pessi",
                            Rarete = "Rare"
                        },
                        new
                        {
                            Id = 17,
                            Attack = 8,
                            Cost = 6,
                            Health = 4,
                            ImageUrl = "https://i.ytimg.com/vi/5DaQZPus0S4/sddefault.jpg",
                            Name = "Bombardino Crocodilo",
                            Rarete = "Légendaire"
                        },
                        new
                        {
                            Id = 18,
                            Attack = 4,
                            Cost = 5,
                            Health = 4,
                            ImageUrl = "https://platform.polygon.com/wp-content/uploads/sites/2/2025/04/CJ1.jpg?quality=90&strip=all&crop=11.73046566693,0,76.53906866614,100",
                            Name = "Chicken Jockey",
                            Rarete = "Épique"
                        },
                        new
                        {
                            Id = 19,
                            Attack = 6,
                            Cost = 5,
                            Health = 2,
                            ImageUrl = "https://i1.sndcdn.com/artworks-VPd3jo9czP2OCWDf-eGwrTA-t500x500.png",
                            Name = "Evil Chicken Jockey",
                            Rarete = "Épique"
                        },
                        new
                        {
                            Id = 20,
                            Attack = 1,
                            Cost = 2,
                            Health = 3,
                            ImageUrl = "https://static.wikia.nocookie.net/11868989-ce9d-4b44-9daf-3bb2e2393c60/scale-to-width/755",
                            Name = "Gros Sus",
                            Rarete = "Commune"
                        });
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonnaieRecueCreation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonnaieRecueDefaite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonnaieRecueVictoire")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxCardsPerDeck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxDecks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nbCardToDraw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qtManaPerTurn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonnaieRecueCreation = 150,
                            MonnaieRecueDefaite = 15,
                            MonnaieRecueVictoire = 100,
                            maxCardsPerDeck = 30,
                            maxDecks = 5,
                            nbCardToDraw = 4,
                            qtManaPerTurn = 3
                        });
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMatchCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerATurn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerDataAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerDataBId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserBId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDataAId");

                    b.HasIndex("PlayerDataBId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.MatchPlayerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayersData");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.PlayableCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchPlayerDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchPlayerDataId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchPlayerDataId2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchPlayerDataId3")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("MatchPlayerDataId");

                    b.HasIndex("MatchPlayerDataId1");

                    b.HasIndex("MatchPlayerDataId2");

                    b.HasIndex("MatchPlayerDataId3");

                    b.ToTable("PlayableCard");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ELO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("nbDefaites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nbVictoires")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ELO = 1000,
                            Money = 15000,
                            Name = "Test player 1",
                            UserId = "User1Id",
                            nbDefaites = 0,
                            nbVictoires = 0
                        },
                        new
                        {
                            Id = 2,
                            ELO = 750,
                            Money = 4000,
                            Name = "Test player 2",
                            UserId = "User2Id",
                            nbDefaites = 0,
                            nbVictoires = 0
                        });
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.StartingCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("StartingCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2
                        },
                        new
                        {
                            Id = 3,
                            CardId = 3
                        },
                        new
                        {
                            Id = 4,
                            CardId = 1
                        },
                        new
                        {
                            Id = 5,
                            CardId = 2
                        },
                        new
                        {
                            Id = 6,
                            CardId = 3
                        },
                        new
                        {
                            Id = 7,
                            CardId = 4
                        },
                        new
                        {
                            Id = 8,
                            CardId = 5
                        },
                        new
                        {
                            Id = 9,
                            CardId = 6
                        },
                        new
                        {
                            Id = 10,
                            CardId = 4
                        },
                        new
                        {
                            Id = 11,
                            CardId = 5
                        },
                        new
                        {
                            Id = 12,
                            CardId = 6
                        },
                        new
                        {
                            Id = 13,
                            CardId = 4
                        },
                        new
                        {
                            Id = 14,
                            CardId = 5
                        },
                        new
                        {
                            Id = 15,
                            CardId = 6
                        },
                        new
                        {
                            Id = 16,
                            CardId = 13
                        });
                });

            modelBuilder.Entity("DeckOwnedCard", b =>
                {
                    b.HasOne("Models.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.OwnedCard", null)
                        .WithMany()
                        .HasForeignKey("OwnedCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Models.CardPower", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany("CardPowers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.Power", "Power")
                        .WithMany("CardPowers")
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Power");
                });

            modelBuilder.Entity("Models.Models.Deck", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Player", "Player")
                        .WithMany("Decks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Models.Models.OwnedCard", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Models.Models.PlayableCardStatus", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.PlayableCard", "PlayableCard")
                        .WithMany("PlayableCardStatus")
                        .HasForeignKey("PlayableCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayableCard");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Match", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", "PlayerDataA")
                        .WithMany()
                        .HasForeignKey("PlayerDataAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", "PlayerDataB")
                        .WithMany()
                        .HasForeignKey("PlayerDataBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlayerDataA");

                    b.Navigation("PlayerDataB");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.MatchPlayerData", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.PlayableCard", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("BattleField")
                        .HasForeignKey("MatchPlayerDataId");

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("CardsPile")
                        .HasForeignKey("MatchPlayerDataId1");

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("Graveyard")
                        .HasForeignKey("MatchPlayerDataId2");

                    b.HasOne("Super_Cartes_Infinies.Models.MatchPlayerData", null)
                        .WithMany("Hand")
                        .HasForeignKey("MatchPlayerDataId3");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Player", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.StartingCard", b =>
                {
                    b.HasOne("Super_Cartes_Infinies.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Models.Models.Power", b =>
                {
                    b.Navigation("CardPowers");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Card", b =>
                {
                    b.Navigation("CardPowers");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.MatchPlayerData", b =>
                {
                    b.Navigation("BattleField");

                    b.Navigation("CardsPile");

                    b.Navigation("Graveyard");

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.PlayableCard", b =>
                {
                    b.Navigation("PlayableCardStatus");
                });

            modelBuilder.Entity("Super_Cartes_Infinies.Models.Player", b =>
                {
                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}